apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-kn-deploy
spec:
  resources:
  - name: source
    type: git
  - name: image
    type: image
  params:
  - name: ARGS
    type: array
    description: Arguments to pass to kn CLI
    default:
      - "help"
  tasks:
  - name: buildah-build
    taskRef:
      name: buildah
    resources:
      inputs:
        - name: source
          resource: source
      outputs:
        - name: image
          resource: image
  - name: kn-deploy
    taskRef:
      name: kn
    runAfter:
      - buildah-build
    resources:
      inputs:
      - name: image
        resource: image
        from:
          - buildah-build
    params:
    - name: ARGS
      value:
        - "$(params.ARGS)"
