apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: build-kn-deploy-
spec:
  serviceAccount: kn-deployer-account
  pipelineRef:
    name: build-kn-deploy
  params:
    - name: service
      value: "svc"
    - name: force
      value: "true"
  resources:
    - name: source
      resourceRef:
        name: build-kn-deploy-source
    - name: image
      resourceRef:
        name: build-kn-deploy-image
