apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: kn-service-update-
spec:
  serviceAccountName: kn-deployer-account
  pipelineRef:
    name: kn-service-update
  resources:
    - name: image
      resourceRef:
        name: kn-service-update-image
  params:
    - name: ARGS
      value:
        - "service"
        - "update"
        - "hello"
        - "--revision-name=hello-v2"
        - "--image=$(inputs.resources.image.url)"
        - "--env=TARGET=v2"
        - "--service-account=kn-deployer-account"
