apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: kn-service-traffic-splitting
spec:
  resources:
  - name: image
    type: image
  params:
  - name: ARGS
    type: array
    description: Arguments to pass to kn CLI
    default:
      - "help"
  tasks:
  - name: kn-service-traffic-splitting
    taskRef:
      name: kn
    resources:
      inputs:
      - name: image
        resource: image
    params:
    - name: kn-image
      value: "gcr.io/knative-nightly/knative.dev/client/cmd/kn"
    - name: ARGS
      value:
        - "$(params.ARGS)"
