apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: kn-service-traffic-splitting-
spec:
  serviceAccount: kn-deployer-account
  pipelineRef:
    name: kn-service-traffic-splitting
  params:
    - name: ARGS
      value:
        - "service"
        - "update"
        - "hello"
        - "--tag=hello-v1=v1"
        - "--tag=hellov-2=v2"
        - "--traffic=v1=90"
        - "--traffic=v2=10"
